from sqlalchemy import Column, String, DateTime, Float, Integer
from sqlalchemy.ext.declarative import declarative_base


class History(declarative_base()):
    __tablename__ = 'history'

    symbol = Column(String(20), primary_key=True, nullable=False)
    width = Column(String(10), primary_key=True, nullable=False)
    open_time = Column(DateTime, primary_key=True, nullable=False)
    open = Column(Float, primary_key=False, nullable=False)
    high = Column(Float, primary_key=False, nullable=False)
    low = Column(Float, primary_key=False, nullable=False)
    close = Column(Float, primary_key=False, nullable=False)
    number_trades = Column(Integer, primary_key=False, nullable=False)
    volume = Column(Float, primary_key=False, nullable=False)
    close_time = Column(DateTime, primary_key=False, nullable=False)
    momentum_ao = Column(Float, primary_key=False, nullable=False)
    momentum_kama = Column(Float, primary_key=False, nullable=False)
    momentum_mfi = Column(Float, primary_key=False, nullable=False)
    momentum_roc = Column(Float, primary_key=False, nullable=False)
    momentum_rsi = Column(Float, primary_key=False, nullable=False)
    momentum_stoch = Column(Float, primary_key=False, nullable=False)
    momentum_stoch_signal = Column(Float, primary_key=False, nullable=False)
    momentum_tsi = Column(Float, primary_key=False, nullable=False)
    momentum_uo = Column(Float, primary_key=False, nullable=False)
    momentum_wr = Column(Float, primary_key=False, nullable=False)
    trend_adx_neg = Column(Float, primary_key=False, nullable=False)
    trend_adx_pos = Column(Float, primary_key=False, nullable=False)
    trend_aroon_down = Column(Float, primary_key=False, nullable=False)
    trend_aroon_ind = Column(Float, primary_key=False, nullable=False)
    trend_aroon_up = Column(Float, primary_key=False, nullable=False)
    trend_cci = Column(Float, primary_key=False, nullable=False)
    trend_dpo = Column(Float, primary_key=False, nullable=False)
    trend_ema_fast = Column(Float, primary_key=False, nullable=False)
    trend_ema_slow = Column(Float, primary_key=False, nullable=False)
    trend_ichimoku_a = Column(Float, primary_key=False, nullable=False)
    trend_ichimoku_b = Column(Float, primary_key=False, nullable=False)
    trend_kst = Column(Float, primary_key=False, nullable=False)
    trend_kst_diff = Column(Float, primary_key=False, nullable=False)
    trend_kst_sig = Column(Float, primary_key=False, nullable=False)
    trend_macd = Column(Float, primary_key=False, nullable=False)
    trend_macd_diff = Column(Float, primary_key=False, nullable=False)
    trend_macd_signal = Column(Float, primary_key=False, nullable=False)
    trend_mass_index = Column(Float, primary_key=False, nullable=False)
    trend_psar = Column(Float, primary_key=False, nullable=False)
    trend_psar_up = Column(Float, primary_key=False, nullable=False)
    trend_psar_down = Column(Float, primary_key=False, nullable=False)
    trend_psar_up_indicator = Column(Float, primary_key=False, nullable=False)
    trend_psar_down_indicator = Column(Float, primary_key=False, nullable=False)
    trend_trix = Column(Float, primary_key=False, nullable=False)
    trend_visual_ichimoku_a = Column(Float, primary_key=False, nullable=False)
    trend_visual_ichimoku_b = Column(Float, primary_key=False, nullable=False)
    volatility_atr = Column(Float, primary_key=False, nullable=False)
    volatility_bbh = Column(Float, primary_key=False, nullable=False)
    volatility_bbhi = Column(Float, primary_key=False, nullable=False)
    volatility_bbl = Column(Float, primary_key=False, nullable=False)
    volatility_bbli = Column(Float, primary_key=False, nullable=False)
    volatility_bbm = Column(Float, primary_key=False, nullable=False)
    volatility_bbw = Column(Float, primary_key=False, nullable=False)
    volatility_dch = Column(Float, primary_key=False, nullable=False)
    volatility_dchi = Column(Float, primary_key=False, nullable=False)
    volatility_dcl = Column(Float, primary_key=False, nullable=False)
    volatility_dcli = Column(Float, primary_key=False, nullable=False)
    volatility_kcc = Column(Float, primary_key=False, nullable=False)
    volatility_kch = Column(Float, primary_key=False, nullable=False)
    volatility_kchi = Column(Float, primary_key=False, nullable=False)
    volatility_kcl = Column(Float, primary_key=False, nullable=False)
    volatility_kcli = Column(Float, primary_key=False, nullable=False)
