runtime: nodejs10
manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: 'production'
  PORT: 8080

  BINANCE_APIKEY: ''
  BINANCE_APISECRET: ''

  DB_SOCKET: ''
  DB_USER: ''
  DB_PASS: ''
  DB_NAME: ''

  SYMBOLS: ''
  INTERVALS: ''