export class History {
	_HEADER = ['OPEN_TIME', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME', 'CLOSE_TIME', 'QUOTE_ASSET_VOLUME', 'NUMBER_TRADES', 'TAKER_BASE_ASSET_VOLUME', 'TAKER_QUOTE_ASSET_VOLUME', 'IGNORE', 'MACD', 'MACD_SIGNAL', 'MACD_DIFF', 'UPPERBAND', 'LOWERBAND'];
	OPEN_TIME: number;
	OPEN: number;
	HIGH: number;
	LOW: number;
	CLOSE: number;
	VOLUME: number;
	CLOSE_TIME: number;
	QUOTE_ASSET_VOLUME: number;
	NUMBER_TRADES: number;
	TAKER_BASE_ASSET_VOLUME: number;
	TAKER_QUOTE_ASSET_VOLUME: number;
	IGNORE: number;
	MACD: number;
	MACD_SIGNAL: number;
	MACD_DIFF: number;
	UPPERBAND: number;
	LOWERBAND: number;
}
